---
 - name: Download WordPress  
   get_url: 
     url=https://wordpress.org/latest.tar.gz 
     dest=/tmp/wordpress.tar.gz
     validate_certs=no

 - name: Extract WordPress  
   unarchive: 
     src=/tmp/wordpress.tar.gz 
     dest=/var/www/
     copy=no
   sudo: yes

 - name: Update default Apache site
   sudo: yes
   lineinfile: 
     dest=/etc/apache2/sites-enabled/000-default.conf 
     regexp="(.)+DocumentRoot /var/www/html"
     line="DocumentRoot /var/www/wordpress"
   notify:
     - restart apache

 - name: Copying the Zipped file to the remote server
   copy:
     src: /home/nginxserver/loadbalancer/wordpress/wp-config.php
     dest: /var/www/wordpress/








